<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class BulkProcessStatusRequest extends AbstractModel
{
    protected static $modelDefinition = [
        'processStatusQueries' => [ 'model' => ProcessStatusId::class, 'array' => true ],
    ];

    /**
     * @var ProcessStatusId[]
     */
    public $processStatusQueries;
}
