<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class BulkCommissionResponse extends AbstractModel
{
    protected static $modelDefinition = [
        'commissions' => [ 'model' => Commission::class, 'array' => true ],
    ];

    /**
     * @var Commission[]
     */
    public $commissions;
}
