<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class BulkCommissionQuery extends AbstractModel
{
    protected static $modelDefinition = [
        'ean' => [ 'model' => null, 'array' => false ],
        'condition' => [ 'model' => null, 'array' => false ],
        'unitPrice' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var string The EAN number associated with this product.
     */
    public $ean;

    /**
     * @var string The condition of the offer.
     */
    public $condition;

    /**
     * @var float The price of the product with a period as a decimal separator. The price should always have two decimals precision.
     */
    public $unitPrice;
}
