<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class Fulfilment extends AbstractModel
{
    protected static $modelDefinition = [
        'method' => [ 'model' => null, 'array' => false ],
        'deliveryCode' => [ 'model' => null, 'array' => false ],
        'pickUpPoints' => [ 'model' => PickUpPoint::class, 'array' => true ],
    ];

    /**
     * @var string Specifies whether this shipment has been fulfilled by the retailer (FBR) or fulfilled by bol.com (FBB). Defaults to FBR.
     */
    public $method;

    /**
     * @var string The delivery promise that applies to this offer. This value will only be used in combination with fulfilmentMethod 'FBR'.
     */
    public $deliveryCode;

    /**
     * @var PickUpPoint[] Indicates whether this order is shipped to a Pick Up Point.
     */
    public $pickUpPoints;
}
