<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class Inbounds extends AbstractModel
{
    protected static $modelDefinition = [
        'inbounds' => [ 'model' => ReducedInbound::class, 'array' => true ],
    ];

    /**
     * @var ReducedInbound[] An inbound shipment.
     */
    public $inbounds;
}
