<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class InboundProductRequest extends AbstractModel
{
    protected static $modelDefinition = [
        'ean' => [ 'model' => null, 'array' => false ],
        'announcedQuantity' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var string The EAN number associated with this product.
     */
    public $ean;

    /**
     * @var int The number of announced items.
     */
    public $announcedQuantity;
}
