<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class KeySetResponse extends AbstractModel
{
    protected static $modelDefinition = [
        'signatureKeys' => [ 'model' => KeySet::class, 'array' => true ],
    ];

    /**
     * @var KeySet[]
     */
    public $signatureKeys;
}
