<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class OfferInsights extends AbstractModel
{
    protected static $modelDefinition = [
        'offerInsights' => [ 'model' => OfferInsight::class, 'array' => true ],
    ];

    /**
     * @var OfferInsight[]
     */
    public $offerInsights;
}
