<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class OrderItem extends AbstractModel
{
    protected static $modelDefinition = [
        'orderItemId' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var string The id for the order item (1 order can have multiple order items).
     */
    public $orderItemId;
}
