<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class Order extends AbstractModel
{
    protected static $modelDefinition = [
        'orderId' => [ 'model' => null, 'array' => false ],
        'pickUpPoint' => [ 'model' => null, 'array' => false ],
        'orderPlacedDateTime' => [ 'model' => null, 'array' => false ],
        'shipmentDetails' => [ 'model' => ShipmentDetails::class, 'array' => false ],
        'billingDetails' => [ 'model' => BillingDetails::class, 'array' => false ],
        'orderItems' => [ 'model' => OrderOrderItem::class, 'array' => true ],
    ];

    /**
     * @var string The order id.
     */
    public $orderId;

    /**
     * @var bool Indicates whether this order is shipped to a Pick Up Point.
     */
    public $pickUpPoint;

    /**
     * @var string The date and time in ISO 8601 format when the order was placed.
     */
    public $orderPlacedDateTime;

    /**
     * @var ShipmentDetails
     */
    public $shipmentDetails;

    /**
     * @var BillingDetails
     */
    public $billingDetails;

    /**
     * @var OrderOrderItem[]
     */
    public $orderItems;

    public function getOrderPlacedDateTime(): ?\DateTime
    {
        if (empty($this->orderPlacedDateTime)) {
            return null;
        }

        return \DateTime::createFromFormat(\DateTime::ATOM, $this->orderPlacedDateTime);
    }
}
