<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class OrderFulfilment extends AbstractModel
{
    protected static $modelDefinition = [
        'method' => [ 'model' => null, 'array' => false ],
        'distributionParty' => [ 'model' => null, 'array' => false ],
        'latestDeliveryDate' => [ 'model' => null, 'array' => false ],
        'exactDeliveryDate' => [ 'model' => null, 'array' => false ],
        'expiryDate' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var string Specifies whether this shipment has been fulfilled by the retailer (FBR) or fulfilled by bol.com (FBB). Defaults to FBR.
     */
    public $method;

    /**
     * @var string The party that manages the distribution, either bol.com or the retailer itself.
     */
    public $distributionParty;

    /**
     * @var string The ultimate delivery date at which this order must be delivered at the customer's shipping address. This field is empty in case the exactDeliveryDate is filled.
     */
    public $latestDeliveryDate;

    /**
     * @var string The exact delivery date at which this order must be delivered at the customer's shipping address. This field is only filled when the customer chose an exact date for delivery. This field is empty in case the latestDeliveryDate is filled.
     */
    public $exactDeliveryDate;

    /**
     * @var string The date this order item will automatically expire and thereby cancelling this order item from the order.
     */
    public $expiryDate;
}
