<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class OrderOffer extends AbstractModel
{
    protected static $modelDefinition = [
        'offerId' => [ 'model' => null, 'array' => false ],
        'reference' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var string Unique identifier for an offer.
     */
    public $offerId;

    /**
     * @var string A user-defined reference tied to the offer upon creating the offer.
     */
    public $reference;
}
