<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class PackageRestrictions extends AbstractModel
{
    protected static $modelDefinition = [
        'maxWeight' => [ 'model' => null, 'array' => false ],
        'maxDimensions' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var string The weight of a package.
     */
    public $maxWeight;

    /**
     * @var string The dimensions of a package.
     */
    public $maxDimensions;
}
