<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class Pricing extends AbstractModel
{
    protected static $modelDefinition = [
        'bundlePrices' => [ 'model' => BundlePrice::class, 'array' => true ],
    ];

    /**
     * @var BundlePrice[] A set of prices (containing a quantity and selling price) that apply to this offer.
     */
    public $bundlePrices;
}
