<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ProductContentResponse extends AbstractModel
{
    protected static $modelDefinition = [
        'internalReference' => [ 'model' => null, 'array' => false ],
        'rejectedAttributes' => [ 'model' => RejectedAttributeResponse::class, 'array' => true ],
        'status' => [ 'model' => null, 'array' => false ],
        'errorCode' => [ 'model' => null, 'array' => false ],
        'errorDescription' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var string A user defined unique reference to identify the products in the upload.
     */
    public $internalReference;

    /**
     * @var RejectedAttributeResponse[]
     */
    public $rejectedAttributes;

    /**
     * @var string The end status of the rejected attribute.
     */
    public $status;

    /**
     * @var int The rejection error code.
     */
    public $errorCode;

    /**
     * @var string The rejection error message explains why the value was rejected.
     */
    public $errorDescription;
}
