<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ProductContent extends AbstractModel
{
    protected static $modelDefinition = [
        'internalReference' => [ 'model' => null, 'array' => false ],
        'attributes' => [ 'model' => Attribute::class, 'array' => true ],
    ];

    /**
     * @var string A user defined unique reference to identify the products in the upload.
     */
    public $internalReference;

    /**
     * @var Attribute[] A list of attributes.
     */
    public $attributes;
}
