<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ProductLabel extends AbstractModel
{
    protected static $modelDefinition = [
        'ean' => [ 'model' => null, 'array' => false ],
        'quantity' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var string The EAN number associated with this product.
     */
    public $ean;

    /**
     * @var int Number of products to generate labels for.
     */
    public $quantity;
}
