<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class Product extends AbstractModel
{
    protected static $modelDefinition = [
        'ean' => [ 'model' => null, 'array' => false ],
        'bsku' => [ 'model' => null, 'array' => false ],
        'announcedQuantity' => [ 'model' => null, 'array' => false ],
        'receivedQuantity' => [ 'model' => null, 'array' => false ],
        'state' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var string The EAN number associated with this product.
     */
    public $ean;

    /**
     * @var string The BSKU number associated with this product.
     */
    public $bsku;

    /**
     * @var int The number of announced items.
     */
    public $announcedQuantity;

    /**
     * @var int The number of received items.
     */
    public $receivedQuantity;

    /**
     * @var string The current state of the inbound product.
     */
    public $state;
}
