<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ReducedOrder extends AbstractModel
{
    protected static $modelDefinition = [
        'orderId' => ['model' => null, 'array' => false ],
        'orderPlacedDateTime' => ['model' => null, 'array' => false ],
        'orderItems' => ['model' => ReducedOrderItem::class, 'array' => true ],
    ];

    /**
     * @var string The order id.
     */
    public $orderId;

    /**
     * @var string The date and time in ISO 8601 format when the order was placed.
     */
    public $orderPlacedDateTime;

    /**
     * @var ReducedOrderItem[]
     */
    public $orderItems;

    public function getOrderPlacedDateTime(): ?\DateTime
    {
        if (empty($this->orderPlacedDateTime)) {
            return null;
        }

        return \DateTime::createFromFormat(\DateTime::ATOM, $this->orderPlacedDateTime);
    }
}
