<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ReducedShipment extends AbstractModel
{
    protected static $modelDefinition = [
        'shipmentId' => [ 'model' => null, 'array' => false ],
        'shipmentDateTime' => [ 'model' => null, 'array' => false ],
        'shipmentReference' => [ 'model' => null, 'array' => false ],
        'order' => [ 'model' => ReducedShipmentOrder::class, 'array' => false ],
        'shipmentItems' => [ 'model' => ReducedShipmentItem::class, 'array' => true ],
        'transport' => [ 'model' => ReducedTransport::class, 'array' => false ],
    ];

    /**
     * @var int A unique identifier for this shipment.
     */
    public $shipmentId;

    /**
     * @var string The date and time in ISO 8601 format when the order item was shipped.
     */
    public $shipmentDateTime;

    /**
     * @var string Reference supplied by the user when this item was shipped.
     */
    public $shipmentReference;

    /**
     * @var ReducedShipmentOrder
     */
    public $order;

    /**
     * @var ReducedShipmentItem[]
     */
    public $shipmentItems;

    /**
     * @var ReducedTransport
     */
    public $transport;

    public function getShipmentDateTime(): ?\DateTime
    {
        if (empty($this->shipmentDateTime)) {
            return null;
        }

        return \DateTime::createFromFormat(\DateTime::ATOM, $this->shipmentDateTime);
    }
}
