<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ReducedOrders extends AbstractModel
{

    /**
     * @var ReducedOrder[]
     */
    public $orders;
}
