<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class RejectionError extends AbstractModel
{
    protected static $modelDefinition = [
        'code' => [ 'model' => null, 'array' => false ],
        'message' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var int The rejection error code.
     */
    public $code;

    /**
     * @var string The rejection error message explains why the value was rejected.
     */
    public $message;
}
