<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ReturnsResponse extends AbstractModel
{
    protected static $modelDefinition = [
        'returns' => [ 'model' => ReducedReturn::class, 'array' => true ],
    ];

    /**
     * @var ReducedReturn[]
     */
    public $returns;
}
