<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ReturnObject extends AbstractModel
{
    protected static $modelDefinition = [
        'returnId' => [ 'model' => null, 'array' => false ],
        'registrationDateTime' => [ 'model' => null, 'array' => false ],
        'fulfilmentMethod' => [ 'model' => null, 'array' => false ],
        'returnItems' => [ 'model' => ReturnItem::class, 'array' => true ],
    ];

    /**
     * @var int Unique identifier for a return.
     */
    public $returnId;

    /**
     * @var string The date and time in ISO 8601 format when this return was registered.
     */
    public $registrationDateTime;

    /**
     * @var string Specifies whether this shipment has been fulfilled by the retailer (FBR) or fulfilled by bol.com (FBB). Defaults to FBR.
     */
    public $fulfilmentMethod;

    /**
     * @var ReturnItem[]
     */
    public $returnItems;

    public function getRegistrationDateTime(): ?\DateTime
    {
        if (empty($this->registrationDateTime)) {
            return null;
        }

        return \DateTime::createFromFormat(\DateTime::ATOM, $this->registrationDateTime);
    }
}
