<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class SalesForecastResponse extends AbstractModel
{
    protected static $modelDefinition = [
        'name' => [ 'model' => null, 'array' => false ],
        'type' => [ 'model' => null, 'array' => false ],
        'total' => [ 'model' => Total::class, 'array' => false ],
        'countries' => [ 'model' => Countries::class, 'array' => true ],
        'periods' => [ 'model' => Period::class, 'array' => true ],
    ];

    /**
     * @var string Indicator name.
     */
    public $name;

    /**
     * @var string Interpretation of the data that applies to this measurement.
     */
    public $type;

    /**
     * @var Total
     */
    public $total;

    /**
     * @var Countries[]
     */
    public $countries;

    /**
     * @var Period[]
     */
    public $periods;
}
