<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ShipmentRequest extends AbstractModel
{
    protected static $modelDefinition = [
        'orderItems' => [ 'model' => OrderItem::class, 'array' => true ],
        'shipmentReference' => [ 'model' => null, 'array' => false ],
        'shippingLabelId' => [ 'model' => null, 'array' => false ],
        'transport' => [ 'model' => TransportInstruction::class, 'array' => false ],
    ];

    /**
     * @var OrderItem[] List of order items to ship. Order item id's must belong to the same order.
     */
    public $orderItems;

    /**
     * @var string A user-defined reference that you can provide to add to the shipment. Can be used for own administration purposes.
     */
    public $shipmentReference;

    /**
     * @var string The identifier of the purchased shipping label.
     */
    public $shippingLabelId;

    /**
     * @var TransportInstruction
     */
    public $transport;
}
