<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ShipmentResponse extends AbstractModel
{
    protected static $modelDefinition = [
        'shipments' => [ 'model' => ReducedShipment::class, 'array' => true ],
    ];

    /**
     * @var ReducedShipment[]
     */
    public $shipments;
}
