<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class StateTransition extends AbstractModel
{
    protected static $modelDefinition = [
        'state' => [ 'model' => null, 'array' => false ],
        'stateDateTime' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var string The state that was transitioned into.
     */
    public $state;

    /**
     * @var string The transition date and time in ISO 8601 format.
     */
    public $stateDateTime;

    public function getStateDateTime(): ?\DateTime
    {
        if (empty($this->stateDateTime)) {
            return null;
        }

        return \DateTime::createFromFormat(\DateTime::ATOM, $this->stateDateTime);
    }
}
