<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class SubscriptionsResponse extends AbstractModel
{
    protected static $modelDefinition = [
        'subscriptions' => [ 'model' => SubscriptionResponse::class, 'array' => true ],
    ];

    /**
     * @var SubscriptionResponse[]
     */
    public $subscriptions;
}
