<?php

namespace Picqer\BolRetailerV4\Model;

// This class is auto generated by OpenApi\ModelGenerator
class Violation extends AbstractModel
{
    protected static $modelDefinition = [
        'name' => [ 'model' => null, 'array' => false ],
        'reason' => [ 'model' => null, 'array' => false ],
    ];

    /**
     * @var string Describes the origin of the error, for instance a field or query parameter validation error.
     */
    public $name;

    /**
     * @var string Detailed description of the validation error that caused the problem.
     */
    public $reason;
}
