<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ChangeTransportRequestTransporterCode: string
{
    case BRIEFPOST = 'BRIEFPOST';
    case UPS = 'UPS';
    case TNT = 'TNT';
    case TNT_EXTRA = 'TNT-EXTRA';
    case TNT_BRIEF = 'TNT_BRIEF';
    case TNT_EXPRESS = 'TNT-EXPRESS';
    case DYL = 'DYL';
    case DPD_NL = 'DPD-NL';
    case DPD_BE = 'DPD-BE';
    case BPOST_BE = 'BPOST_BE';
    case BPOST_BRIEF = 'BPOST_BRIEF';
    case DHLFORYOU = 'DHLFORYOU';
    case GLS = 'GLS';
    case FEDEX_NL = 'FEDEX_NL';
    case FEDEX_BE = 'FEDEX_BE';
    case OTHER = 'OTHER';
    case DHL = 'DHL';
    case DHL_DE = 'DHL_DE';
    case DHL_GLOBAL_MAIL = 'DHL-GLOBAL-MAIL';
    case TSN = 'TSN';
    case FIEGE = 'FIEGE';
    case TRANSMISSION = 'TRANSMISSION';
    case PARCEL_NL = 'PARCEL-NL';
    case LOGOIX = 'LOGOIX';
    case PACKS = 'PACKS';
    case COURIER = 'COURIER';
    case TRUNKRS = 'TRUNKRS';
    case CYCLOON = 'CYCLOON';
}
