<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ConditionName: string
{
    case NEW = 'NEW';
    case AS_NEW = 'AS_NEW';
    case GOOD = 'GOOD';
    case REASONABLE = 'REASONABLE';
    case MODERATE = 'MODERATE';
}
