<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum CustomerDetailsSalutation: string
{
    case MALE = 'MALE';
    case FEMALE = 'FEMALE';
    case UNKNOWN = 'UNKNOWN';
}
