<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum DeliveryOptionLabelType: string
{
    case PARCEL = 'PARCEL';
    case MAILBOX = 'MAILBOX';
    case MAILBOX_LIGHT = 'MAILBOX_LIGHT';
}
