<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetCompetingOffersCondition: string
{
    case ALL = 'ALL';
    case BAD = 'BAD';
    case MODERATE = 'MODERATE';
    case REASONABLE = 'REASONABLE';
    case GOOD = 'GOOD';
    case AS_NEW = 'AS_NEW';
    case NEW = 'NEW';
    case REFURBISHED_A = 'REFURBISHED_A';
    case REFURBISHED_B = 'REFURBISHED_B';
    case REFURBISHED_C = 'REFURBISHED_C';
}
