<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetInvoiceRequestsState: string
{
    case OPEN = 'OPEN';
    case UPLOAD_ERROR = 'UPLOAD_ERROR';
    case ALL = 'ALL';
}
