<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetInventoryStock: string
{
    case SUFFICIENT = 'SUFFICIENT';
    case INSUFFICIENT = 'INSUFFICIENT';
}
