<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetLoadCarrierLabelsLabelType: string
{
    case WAREHOUSE = 'WAREHOUSE';
    case TRANSPORT = 'TRANSPORT';
}
