<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetOrdersStatus: string
{
    case OPEN = 'OPEN';
    case SHIPPED = 'SHIPPED';
    case ALL = 'ALL';
}
