<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetOrdersFulfilmentMethod: string
{
    case FBR = 'FBR';
    case FBB = 'FBB';
    case ALL = 'ALL';
}
