<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetProductRanksAcceptLanguage: string
{
    case NL_NL = 'nl-NL';
    case NL = 'nl';
    case NL_BE = 'nl-BE';
    case FR = 'fr';
    case FR_BE = 'fr-BE';
}
