<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum GetProductPlacementAcceptLanguage: string
{
    case NL = 'nl';
    case NL_BE = 'nl-BE';
    case FR_BE = 'fr-BE';
}
