<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum InvalidReplenishmentLineType: string
{
    case UNKNOWN_FBB_PRODUCT = 'UNKNOWN_FBB_PRODUCT';
    case UNKNOWN_EAN_INVENTORY_RELATION = 'UNKNOWN_EAN_INVENTORY_RELATION';
}
