<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum LoadCarrierTransportState: string
{
    case ANNOUNCED = 'ANNOUNCED';
    case PICKED_UP = 'PICKED_UP';
    case UNDERWAY = 'UNDERWAY';
    case DELAYED = 'DELAYED';
    case ARRIVED = 'ARRIVED';
    case ERROR = 'ERROR';
}
