<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum OrderFulfilmentDistributionParty: string
{
    case RETAILER = 'RETAILER';
    case BOL = 'BOL';
}
