<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum PerformanceIndicatorType: string
{
    case PERCENTAGE = 'PERCENTAGE';
    case AVERAGE = 'AVERAGE';
}
