<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum PickupAppointmentCancellationReason: string
{
    case UNKNOWN_ADDRESS = 'UNKNOWN_ADDRESS';
    case NOT_READY = 'NOT_READY';
    case NO_LABEL = 'NO_LABEL';
    case WRONG_PACKAGE = 'WRONG_PACKAGE';
    case NOT_AT_HOME = 'NOT_AT_HOME';
    case OTHER_REASON = 'OTHER_REASON';
    case REQUEST_FROM_RETAILER = 'REQUEST_FROM_RETAILER';
}
