<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ProcessStatusStatus: string
{
    case PENDING = 'PENDING';
    case SUCCESS = 'SUCCESS';
    case FAILURE = 'FAILURE';
    case TIMEOUT = 'TIMEOUT';
}
