<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ProductAssetsUsage: string
{
    case PRIMARY = 'PRIMARY';
    case ADDITIONAL = 'ADDITIONAL';
    case IMAGE = 'IMAGE';
}
