<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ProductAssetsVariantsMimeType: string
{
    case IMAGE_JPEG = 'image/jpeg';
    case APPLICATION_PDF = 'application/pdf';
    case APPLICATION_X_MPEGURL = 'application/x-mpegurl';
    case VIDEO_MP4 = 'video/mp4';
}
