<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ProductListRequestSort: string
{
    case RELEVANCE = 'RELEVANCE';
    case POPULARITY = 'POPULARITY';
    case PRICE_ASC = 'PRICE_ASC';
    case PRICE_DESC = 'PRICE_DESC';
    case RELEASE_DATE = 'RELEASE_DATE';
    case RATING = 'RATING';
    case WISHLIST = 'WISHLIST';
}
