<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ReducedPromotionPromotionType: string
{
    case AWARENESS = 'AWARENESS';
    case PRICE_OFF = 'PRICE_OFF';
}
