<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ReplenishmentLineLineState: string
{
    case ANNOUNCED = 'ANNOUNCED';
    case UNANNOUNCED = 'UNANNOUNCED';
    case UNKNOWN = 'UNKNOWN';
}
