<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum RetailerInformationResponseRatingMethod: string
{
    case ALL_REVIEWS = 'ALL_REVIEWS';
    case THREE_MONTHS = 'THREE_MONTHS';
}
