<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum ShipmentFulfilmentDistributionParty: string
{
    case RETAILER = 'RETAILER';
    case BOL = 'BOL';
}
