<?php

namespace Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum StatusTransitionsStatus: string
{
    case INVOICE_REQUESTED = 'INVOICE_REQUESTED';
    case INVOICE_UPLOADED = 'INVOICE_UPLOADED';
    case INVOICE_INCORRECT = 'INVOICE_INCORRECT';
    case INVOICE_VIRUS_DETECTED = 'INVOICE_VIRUS_DETECTED';
    case FINISHED = 'FINISHED';
}
