<?php

namespace Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
enum SubscriptionRequestSubscriptionType: string
{
    case WEBHOOK = 'WEBHOOK';
    case GCP_PUBSUB = 'GCP_PUBSUB';
}
