<?php

namespace Picqer\BolRetailerV6\Model;

// This class is auto generated by OpenApi\ModelGenerator
class Asset extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'url' => [ 'model' => null, 'array' => false ],
            'labels' => [ 'model' => null, 'array' => true ],
        ];
    }

    /**
     * @var string The url of the asset that will be used to do the actual uploading.
     */
    public $url;

    /**
     * @var array The labels characterizing the asset, for detailed information see the datamodel.
     */
    public $labels = [];
}
