<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class BulkCommissionRatesMultiStatusResponse extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'successfulQueries' => [ 'model' => CommissionSuccessfulQuery::class, 'enum' => null, 'array' => true ],
            'failedQueries' => [ 'model' => CommissionFailedQuery::class, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var CommissionSuccessfulQuery[]
     */
    public $successfulQueries = [];

    /**
     * @var CommissionFailedQuery[]
     */
    public $failedQueries = [];
}
