<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class CommissionFailedQuery extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'index' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'status' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'violations' => [ 'model' => Violation::class, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var float This provides the location of the entity where it was provided in the original response body.
     */
    public $index;

    /**
     * @var int HTTP status code for individual entity operation.
     */
    public $status;

    /**
     * @var Violation[] Outlines the list of violations encountered in the API for the specific index detailing the
     * nature and reason for the issue.
     */
    public $violations = [];
}
