<?php

namespace Jobjen\BolRetailerV10\Model;

use Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class CreateUnpublishedOfferReportRequest extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'format' => [ 'model' => null, 'enum' => Enum\CreateUnpublishedOfferReportRequestFormat::class, 'array' => false ],
        ];
    }

    /**
     * @var Enum\CreateUnpublishedOfferReportRequestFormat The file format in which to return the export.
     */
    public $format;
}
