<?php

namespace Picqer\BolRetailerV5\Model;

// This class is auto generated by OpenApi\ModelGenerator
class DeliveryWindowsForInboundShipments extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'timeSlots' => [ 'model' => TimeSlot::class, 'array' => true ],
        ];
    }

    /**
     * @var TimeSlot[] An available timeslot to be reserved for inbound shipments.
     */
    public $timeSlots = [];
}
