<?php

namespace Jobjen\BolRetailerV10\Model;

use Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class InvoiceRequests extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'shipmentId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'orderId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'customerAccountNumber' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'billingDetails' => [ 'model' => InvoiceRequestsBillingDetails::class, 'enum' => null, 'array' => false ],
            'products' => [ 'model' => InvoiceRequestsProducts::class, 'enum' => null, 'array' => true ],
            'status' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'statusTransitions' => [ 'model' => StatusTransitions::class, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var string The id of the shipment associated with this invoice request.
     */
    public $shipmentId;

    /**
     * @var string The id of the order associated with this shipment.
     */
    public $orderId;

    /**
     * @var string The account of the customer within bol.com associated with this shipment.
     */
    public $customerAccountNumber;

    /**
     * @var InvoiceRequestsBillingDetails The details of the customer that is responsible for the financial fulfillment
     * of this shipment.
     */
    public $billingDetails;

    /**
     * @var InvoiceRequestsProducts[]
     */
    public $products = [];

    /**
     * @var string The current status of the invoice request.
     */
    public $status;

    /**
     * @var StatusTransitions[]
     */
    public $statusTransitions = [];
}
