<?php

namespace Jobjen\BolRetailerV10\Model;

use Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class Link extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'rel' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'href' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'hreflang' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'media' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'title' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'type' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'deprecation' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'profile' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'name' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var string
     */
    public $rel;

    /**
     * @var string
     */
    public $href;

    /**
     * @var string
     */
    public $hreflang;

    /**
     * @var string
     */
    public $media;

    /**
     * @var string
     */
    public $title;

    /**
     * @var string
     */
    public $type;

    /**
     * @var string
     */
    public $deprecation;

    /**
     * @var string
     */
    public $profile;

    /**
     * @var string
     */
    public $name;
}
