<?php

namespace Picqer\BolRetailerV5\Model;

// This class is auto generated by OpenApi\ModelGenerator
class OrderItemCancellation extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'orderItemId' => [ 'model' => null, 'array' => false ],
            'reasonCode' => [ 'model' => null, 'array' => false ],
        ];
    }

    /**
     * @var string The id for the order item (1 order can have multiple order items).
     */
    public $orderItemId;

    /**
     * @var string The code representing the reason for cancellation of this item.
     */
    public $reasonCode;
}
