<?php

namespace Picqer\BolRetailerV10\Model;

// This class is auto generated by OpenApi\ModelGenerator
class Party extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'name' => [ 'model' => null, 'array' => false ],
            'type' => [ 'model' => null, 'array' => false ],
            'role' => [ 'model' => null, 'array' => false ],
        ];
    }

    /**
     * @var string The name of the party involved for this product.
     */
    public $name;

    /**
     * @var string The type of party involved for this product.
     */
    public $type;

    /**
     * @var string The role of the party involved for this product.
     */
    public $role;
}
