<?php

namespace Jobjen\BolRetailerV10\Model;

use Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class ProcessStatus extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'processStatusId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'entityId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'eventType' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'description' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'status' => [ 'model' => null, 'enum' => Enum\ProcessStatusStatus::class, 'array' => false ],
            'errorMessage' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'createTimestamp' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'links' => [ 'model' => Link::class, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var string The process status id.
     */
    public $processStatusId;

    /**
     * @var string The id of the object being processed. For example, in case of a shipment process id, you will receive
     * the id of the order item being processed.
     */
    public $entityId;

    /**
     * @var string Name of the requested action that is being processed.
     */
    public $eventType;

    /**
     * @var string Describes the action that is being processed.
     */
    public $description;

    /**
     * @var Enum\ProcessStatusStatus Status of the action being processed.
     */
    public $status;

    /**
     * @var string Shows error message if applicable.
     */
    public $errorMessage;

    /**
     * @var string Time of creation of the response.
     */
    public $createTimestamp;

    /**
     * @var Link[] Lists available actions applicable to this endpoint.
     */
    public $links = [];
}
