<?php

namespace Jobjen\BolRetailerV10\Model;

use Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class ProductRatingsRating extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'rating' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'count' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var int Scale of the rating provided by the customer.
     */
    public $rating;

    /**
     * @var int The number of ratings for the corresponding scale.
     */
    public $count;
}
