<?php

namespace Picqer\BolRetailerV10\Model;

use Picqer\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class ProductCategoriesResponse extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'categories' => [ 'model' => ProductCategory::class, 'enum' => null, 'array' => true ],
        ];
    }

    /**
     * @var ProductCategory[] A list of product categories and its children.
     */
    public $categories = [];
}
