<?php

namespace Picqer\BolRetailerV10\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ProductListFiltersRequest extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'searchTerm' => [ 'model' => null, 'array' => false ],
            'categoryId' => [ 'model' => null, 'array' => false ],
            'search' => [ 'model' => null, 'array' => false ],
            'category' => [ 'model' => null, 'array' => false ],
        ];
    }

    /**
     * @var string
     */
    public $searchTerm;

    /**
     * @var string
     */
    public $categoryId;

    /**
     * @var string
     */
    public $search;

    /**
     * @var string
     */
    public $category;
}
