<?php

namespace Jobjen\BolRetailerV10\Model;

use Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class ProductAssetsVariants extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'size' => [ 'model' => null, 'enum' => Enum\ProductAssetsVariantsSize::class, 'array' => false ],
            'width' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'height' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'mimeType' => [ 'model' => null, 'enum' => Enum\ProductAssetsVariantsMimeType::class, 'array' => false ],
            'url' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\ProductAssetsVariantsSize The name of the size of the asset, if the asset is an image.
     */
    public $size;

    /**
     * @var int The width of the asset in pixels.
     */
    public $width;

    /**
     * @var int The height of the asset in pixels.
     */
    public $height;

    /**
     * @var Enum\ProductAssetsVariantsMimeType The mime type of the asset.
     */
    public $mimeType;

    /**
     * @var string The URL of the attribute.
     */
    public $url;
}
