<?php

namespace Picqer\BolRetailer\Model;

// This class is auto generated by OpenApi\ModelGenerator
class ProductLabelsRequest extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'labelFormat' => [ 'model' => null, 'array' => false ],
            'products' => [ 'model' => ProductLabelsProduct::class, 'array' => true ],
        ];
    }

    /**
     * @var string The printer format to create labels for.
     */
    public $labelFormat;

    /**
     * @var ProductLabelsProduct[]
     */
    public $products = [];
}
