<?php

namespace Picqer\BolRetailerV5\Model;

// This class is auto generated by OpenApi\ModelGenerator
class RejectedAttributeResponse extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'attributeId' => [ 'model' => null, 'array' => false ],
            'rejectionErrors' => [ 'model' => RejectionError::class, 'array' => true ],
        ];
    }

    /**
     * @var string Identifier of the attribute from the data model.
     */
    public $attributeId;

    /**
     * @var RejectionError[]
     */
    public $rejectionErrors = [];
}
