<?php

namespace Picqer\BolRetailerV5\Model;

// This class is auto generated by OpenApi\ModelGenerator
class RejectionError extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'code' => [ 'model' => null, 'array' => false ],
            'message' => [ 'model' => null, 'array' => false ],
        ];
    }

    /**
     * @var int The rejection error code.
     */
    public $code;

    /**
     * @var string The rejection error message explains why the value was rejected.
     */
    public $message;
}
