<?php

namespace Jobjen\BolRetailerV10\Model;

use Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class RelevanceScore extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'countryCode' => [ 'model' => null, 'enum' => Enum\RelevanceScoreCountryCode::class, 'array' => false ],
            'relevanceScore' => [ 'model' => null, 'enum' => Enum\RelevanceScoreRelevanceScore::class, 'array' => false ],
        ];
    }

    /**
     * @var Enum\RelevanceScoreCountryCode The country for which the relevance score has been calculated against.
     */
    public $countryCode;

    /**
     * @var Enum\RelevanceScoreRelevanceScore The calculated relevance score for the product.
     */
    public $relevanceScore;
}
