<?php

namespace Jobjen\BolRetailerV10\Model;

use Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class ShipmentItem extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'orderItemId' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'fulfilment' => [ 'model' => ShipmentFulfilment::class, 'enum' => null, 'array' => false ],
            'offer' => [ 'model' => OrderOffer::class, 'enum' => null, 'array' => false ],
            'product' => [ 'model' => OrderProduct::class, 'enum' => null, 'array' => false ],
            'quantity' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'unitPrice' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'commission' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var string A unique identifier for the item of the order that was shipped in this shipment.
     */
    public $orderItemId;

    /**
     * @var ShipmentFulfilment
     */
    public $fulfilment;

    /**
     * @var OrderOffer
     */
    public $offer;

    /**
     * @var OrderProduct
     */
    public $product;

    /**
     * @var int Amount of the product being ordered.
     */
    public $quantity;

    /**
     * @var float The selling price to the customer of a single unit including VAT.
     */
    public $unitPrice;

    /**
     * @var float The commission.
     */
    public $commission;
}
