<?php

namespace Jobjen\BolRetailerV10\Model;

use Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class ShipmentFulfilment extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'method' => [ 'model' => null, 'enum' => Enum\ShipmentFulfilmentMethod::class, 'array' => false ],
            'distributionParty' => [ 'model' => null, 'enum' => Enum\ShipmentFulfilmentDistributionParty::class, 'array' => false ],
            'latestDeliveryDate' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var Enum\ShipmentFulfilmentMethod The fulfilment method. Fulfilled by the retailer (FBR) or fulfilled by bol.com
     * (FBB).
     */
    public $method;

    /**
     * @var Enum\ShipmentFulfilmentDistributionParty The party that manages the distribution, either bol.com or the
     * retailer itself.
     */
    public $distributionParty;

    /**
     * @var string The ultimate delivery date at which this order must be delivered at the customer's shipping address.
     * This field is empty in case the exactDeliveryDate is filled.
     */
    public $latestDeliveryDate;
}
