<?php

namespace Picqer\BolRetailerV5\Model;

// This class is auto generated by OpenApi\ModelGenerator
class UpdateLoadCarrier extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'sscc' => [ 'model' => null, 'array' => false ],
        ];
    }

    /**
     * @var string The Serial Shipping Container Code (SSCC) for this load carrier.
     */
    public $sscc;
}
