<?php

namespace Jobjen\BolRetailerV10\Model;

use Jobjen\BolRetailerV10\Enum;

// This class is auto generated by OpenApi\ModelGenerator
class UploadReportAttribute extends AbstractModel
{
    /**
     * Returns the definition of the model: an associative array with field names as key and
     * field definition as value. The field definition contains of
     * model: Model class or null if it is a scalar type
     * array: Boolean whether it is an array
     * @return array The model definition
     */
    public function getModelDefinition(): array
    {
        return [
            'id' => [ 'model' => null, 'enum' => null, 'array' => false ],
            'values' => [ 'model' => UploadReportValue::class, 'enum' => null, 'array' => true ],
            'status' => [ 'model' => null, 'enum' => Enum\UploadReportAttributeStatus::class, 'array' => false ],
            'subStatus' => [ 'model' => null, 'enum' => Enum\UploadReportAttributeSubStatus::class, 'array' => false ],
            'subStatusDescription' => [ 'model' => null, 'enum' => null, 'array' => false ],
        ];
    }

    /**
     * @var string The identifier of the attribute for which the value has changed.
     */
    public $id;

    /**
     * @var UploadReportValue[]
     */
    public $values = [];

    /**
     * @var Enum\UploadReportAttributeStatus The processing state of the submitted attribute.
     */
    public $status;

    /**
     * @var Enum\UploadReportAttributeSubStatus The reason code explaining why the value was rejected.
     */
    public $subStatus;

    /**
     * @var string The reason explaining why the value was rejected.
     */
    public $subStatusDescription;
}
