<?php

namespace Picqer\BolRetailerV4;

// This class is auto generated by OpenApi\ClientGenerator
class Client extends BaseClient
{

    /**
     * Gets a paginated list of all open orders sorted by date in descending order.
     * @param int page The requested page number with a page size of 50 items.
     * @param string fulfilmentMethod The fulfilment method. Fulfilled by the retailer (FBR) or fulfilled by bol.com (FBB).
     * @return Model\ReducedOrders
     * @throws Exception\ConnectException when an error occurred in the HTTP connection.
     * @throws Exception\UnauthorizedException when request was unauthorized.
     * @throws Exception\Exception when something unexpected went wrong.
     */
    public function getOrders(int $page = 1, string $fulfilmentMethod = 'FBR'): Model\ReducedOrders
    {
        $options = [
            'query' => [
                'page' => $page,
                'fulfilment-method' => $fulfilmentMethod,
            ];
        ];

        return $this->request('GET', 'orders', $options, 'ReducedOrders');
    }

    /**
     * Creates a new offer, and adds it to the catalog. After creation, status information can be retrieved to review if the offer is valid and published to the shop.
     * @param Model\CreateOfferRequest createOfferRequest
     * @return Model\ProcessStatus
     * @throws Exception\ConnectException when an error occurred in the HTTP connection.
     * @throws Exception\UnauthorizedException when request was unauthorized.
     * @throws Exception\Exception when something unexpected went wrong.
     */
    public function postOffer(Model\CreateOfferRequest $createOfferRequest): Model\ProcessStatus
    {
        $options = [
            'body' => $createOfferRequest
        ];

        return $this->request('POST', 'offers', $options, 'ProcessStatus');
    }
}
